/**
 * Country photo registry — synced from public/images/destinations/.
 * Run: node scripts/sync-country-images.mjs
 *
 * Add a photo: drop `{country-slug}.jpg` in public/images/destinations/, then sync.
 */
export const COUNTRY_IMAGE_REGISTRY: Record<string, string> = {
  "argentina": "/images/destinations/argentina.jpg",
  "australia": "/images/destinations/australia.jpg",
  "austria": "/images/destinations/austria.jpg",
  "bahamas": "/images/destinations/bahamas.jpg",
  "bahrain": "/images/destinations/bahrain.jpg",
  "barbados": "/images/destinations/barbados.jpg",
  "belgium": "/images/destinations/belgium.jpg",
  "brazil": "/images/destinations/brazil.jpg",
  "canada": "/images/destinations/canada.jpg",
  "chile": "/images/destinations/chile.jpg",
  "china": "/images/destinations/china.jpg",
  "colombia": "/images/destinations/colombia.jpg",
  "costa-rica": "/images/destinations/costa-rica.jpg",
  "denmark": "/images/destinations/denmark.jpg",
  "dominican-republic": "/images/destinations/dominican-republic.jpg",
  "egypt": "/images/destinations/egypt.jpg",
  "fiji": "/images/destinations/fiji.jpg",
  "finland": "/images/destinations/finland.jpg",
  "france": "/images/destinations/france.jpg",
  "germany": "/images/destinations/germany.jpg",
  "iceland": "/images/destinations/iceland.jpg",
  "india": "/images/destinations/india.jpg",
  "indonesia": "/images/destinations/indonesia.jpg",
  "ireland": "/images/destinations/ireland.jpg",
  "italy": "/images/destinations/italy.jpg",
  "jamaica": "/images/destinations/jamaica.jpg",
  "japan": "/images/destinations/japan.jpg",
  "jordan": "/images/destinations/jordan.jpg",
  "kuwait": "/images/destinations/kuwait.jpg",
  "lebanon": "/images/destinations/lebanon.jpg",
  "malaysia": "/images/destinations/malaysia.jpg",
  "maldives": "/images/destinations/maldives.jpg",
  "malta": "/images/destinations/malta.jpg",
  "mexico": "/images/destinations/mexico.jpg",
  "morocco": "/images/destinations/morocco.jpg",
  "netherlands": "/images/destinations/netherlands.jpg",
  "nigeria": "/images/destinations/nigeria.jpg",
  "norway": "/images/destinations/norway.jpg",
  "oman": "/images/destinations/oman.jpg",
  "panama": "/images/destinations/panama.jpg",
  "peru": "/images/destinations/peru.jpg",
  "philippines": "/images/destinations/philippines.jpg",
  "portugal": "/images/destinations/portugal.jpg",
  "puerto-rico": "/images/destinations/puerto-rico.jpg",
  "qatar": "/images/destinations/qatar.jpg",
  "russia": "/images/destinations/russia.jpg",
  "saudi-arabia": "/images/destinations/saudi-arabia.jpg",
  "singapore": "/images/destinations/singapore.jpg",
  "south-africa": "/images/destinations/south-africa.jpg",
  "south-korea": "/images/destinations/south-korea.jpg",
  "spain": "/images/destinations/spain.jpg",
  "sweden": "/images/destinations/sweden.jpg",
  "switzerland": "/images/destinations/switzerland.jpg",
  "thailand": "/images/destinations/thailand.jpg",
  "trinidad-and-tobago": "/images/destinations/trinidad-and-tobago.jpg",
  "turkey": "/images/destinations/turkey.jpg",
  "uae": "/images/destinations/uae.jpg",
  "uk": "/images/destinations/uk.jpg",
  "usa": "/images/destinations/usa.jpg",
  "vietnam": "/images/destinations/vietnam.jpg",
};

/** Regional multi-country products only — never used as a stand-in for a single country. */
export const REGIONAL_IMAGE_REGISTRY: Record<string, string> = {
  africa: "/images/destinations/africa-regional.jpg",
  americas: "/images/destinations/north-america-regional.jpg",
  "north-america": "/images/destinations/north-america-regional.jpg",
  "asia-pacific": "/images/destinations/asia-regional.jpg",
  europe: "/images/destinations/europe-regional.jpg",
  "middle-east": "/images/destinations/middle-east-regional.jpg",
  "south-america": "/images/destinations/south-america-regional.jpg",
  global: "/images/destinations/global-regional.jpg",
  caribbean: "/images/destinations/bahamas.jpg",
};
