/**
 * Country photo registry — synced from public/images/destinations/.
 * Run: node scripts/sync-country-images.mjs
 *
 * Add a photo: drop `{country-slug}.webp` (or .jpg) in public/images/destinations/, then sync.
 */
export const COUNTRY_IMAGE_REGISTRY: Record<string, string> = {
  "argentina": "/images/destinations/argentina.webp",
  "australia": "/images/destinations/australia.webp",
  "austria": "/images/destinations/austria.webp",
  "bahamas": "/images/destinations/bahamas.webp",
  "bahrain": "/images/destinations/bahrain.webp",
  "barbados": "/images/destinations/barbados.webp",
  "belgium": "/images/destinations/belgium.webp",
  "brazil": "/images/destinations/brazil.webp",
  "canada": "/images/destinations/canada.webp",
  "chile": "/images/destinations/chile.webp",
  "china": "/images/destinations/china.webp",
  "colombia": "/images/destinations/colombia.webp",
  "costa-rica": "/images/destinations/costa-rica.webp",
  "denmark": "/images/destinations/denmark.webp",
  "dominican-republic": "/images/destinations/dominican-republic.webp",
  "egypt": "/images/destinations/egypt.webp",
  "fiji": "/images/destinations/fiji.webp",
  "finland": "/images/destinations/finland.webp",
  "france": "/images/destinations/france.webp",
  "germany": "/images/destinations/germany.webp",
  "iceland": "/images/destinations/iceland.webp",
  "india": "/images/destinations/india.webp",
  "indonesia": "/images/destinations/indonesia.webp",
  "ireland": "/images/destinations/ireland.webp",
  "italy": "/images/destinations/italy.webp",
  "jamaica": "/images/destinations/jamaica.webp",
  "japan": "/images/destinations/japan.webp",
  "jordan": "/images/destinations/jordan.webp",
  "kuwait": "/images/destinations/kuwait.webp",
  "lebanon": "/images/destinations/lebanon.webp",
  "malaysia": "/images/destinations/malaysia.webp",
  "maldives": "/images/destinations/maldives.webp",
  "malta": "/images/destinations/malta.webp",
  "mexico": "/images/destinations/mexico.webp",
  "morocco": "/images/destinations/morocco.webp",
  "netherlands": "/images/destinations/netherlands.webp",
  "nigeria": "/images/destinations/nigeria.webp",
  "norway": "/images/destinations/norway.webp",
  "oman": "/images/destinations/oman.webp",
  "panama": "/images/destinations/panama.webp",
  "peru": "/images/destinations/peru.webp",
  "philippines": "/images/destinations/philippines.webp",
  "portugal": "/images/destinations/portugal.webp",
  "puerto-rico": "/images/destinations/puerto-rico.webp",
  "qatar": "/images/destinations/qatar.webp",
  "russia": "/images/destinations/russia.webp",
  "saudi-arabia": "/images/destinations/saudi-arabia.webp",
  "singapore": "/images/destinations/singapore.webp",
  "south-africa": "/images/destinations/south-africa.webp",
  "south-korea": "/images/destinations/south-korea.webp",
  "spain": "/images/destinations/spain.webp",
  "sweden": "/images/destinations/sweden.webp",
  "switzerland": "/images/destinations/switzerland.webp",
  "thailand": "/images/destinations/thailand.webp",
  "trinidad-and-tobago": "/images/destinations/trinidad-and-tobago.webp",
  "turkey": "/images/destinations/turkey.webp",
  "uae": "/images/destinations/uae.webp",
  "uk": "/images/destinations/uk.webp",
  "usa": "/images/destinations/usa.webp",
  "vietnam": "/images/destinations/vietnam.webp",
};

/** Regional multi-country products only — never used as a stand-in for a single country. */
export const REGIONAL_IMAGE_REGISTRY: Record<string, string> = {
  "africa": "/images/destinations/africa-regional.webp",
  "americas": "/images/destinations/north-america-regional.webp",
  "asia-pacific": "/images/destinations/asia-regional.webp",
  "caribbean": "/images/destinations/caribbean-regional.webp",
  "europe": "/images/destinations/europe-regional.webp",
  "global": "/images/destinations/global-regional.webp",
  "middle-east": "/images/destinations/middle-east-regional.webp",
  "north-america": "/images/destinations/north-america-regional.webp",
  "south-america": "/images/destinations/south-america-regional.webp",
};
