import { normalizeCountrySlug } from "@/lib/country-slugs";

const SLUG_ALIASES: Record<string, string> = {
  us: "usa",
  "united-states": "usa",
  gb: "uk",
  "united-kingdom": "uk",
  "united-arab-emirates": "uae",
  korea: "south-korea",
  rusia: "russia",
  "russian-federation": "russia",
};

/** Country slug → flag emoji for plans UI (fallback when API omits flag). */
const COUNTRY_FLAGS: Record<string, string> = {
  usa: "🇺🇸",
  canada: "🇨🇦",
  mexico: "🇲🇽",
  panama: "🇵🇦",
  "costa-rica": "🇨🇷",
  guatemala: "🇬🇹",
  honduras: "🇭🇳",
  belize: "🇧🇿",
  bahamas: "🇧🇸",
  jamaica: "🇯🇲",
  "dominican-republic": "🇩🇴",
  barbados: "🇧🇧",
  "trinidad-and-tobago": "🇹🇹",
  "puerto-rico": "🇵🇷",
  uk: "🇬🇧",
  france: "🇫🇷",
  germany: "🇩🇪",
  italy: "🇮🇹",
  spain: "🇪🇸",
  netherlands: "🇳🇱",
  switzerland: "🇨🇭",
  portugal: "🇵🇹",
  austria: "🇦🇹",
  belgium: "🇧🇪",
  ireland: "🇮🇪",
  sweden: "🇸🇪",
  norway: "🇳🇴",
  denmark: "🇩🇰",
  finland: "🇫🇮",
  iceland: "🇮🇸",
  malta: "🇲🇹",
  russia: "🇷🇺",
  europe: "🇪🇺",
  "regional-europe": "🇪🇺",
  "regional-north-america": "🌎",
  "north-america": "🌎",
  americas: "🌎",
  "regional-asia-pacific": "🌏",
  "asia-pacific": "🌏",
  asia: "🌏",
  "regional-africa": "🌍",
  africa: "🌍",
  "regional-south-america": "🌎",
  "south-america": "🌎",
  "regional-global": "🌐",
  global: "🌐",
  japan: "🇯🇵",
  china: "🇨🇳",
  india: "🇮🇳",
  australia: "🇦🇺",
  singapore: "🇸🇬",
  thailand: "🇹🇭",
  "south-korea": "🇰🇷",
  indonesia: "🇮🇩",
  malaysia: "🇲🇾",
  philippines: "🇵🇭",
  vietnam: "🇻🇳",
  fiji: "🇫🇯",
  maldives: "🇲🇻",
  "saudi-arabia": "🇸🇦",
  uae: "🇦🇪",
  caribbean: "🏝️",
  "regional-caribbean": "🏝️",
  "middle-east": "🕌",
  "regional-middle-east": "🕌",
  qatar: "🇶🇦",
  kuwait: "🇰🇼",
  bahrain: "🇧🇭",
  oman: "🇴🇲",
  turkey: "🇹🇷",
  egypt: "🇪🇬",
  jordan: "🇯🇴",
  lebanon: "🇱🇧",
  brazil: "🇧🇷",
  argentina: "🇦🇷",
  chile: "🇨🇱",
  colombia: "🇨🇴",
  peru: "🇵🇪",
  "south-africa": "🇿🇦",
  nigeria: "🇳🇬",
  morocco: "🇲🇦",
  // Extra coverage for regional hover lists
  poland: "🇵🇱",
  czechia: "🇨🇿",
  "czech-republic": "🇨🇿",
  greece: "🇬🇷",
  hungary: "🇭🇺",
  romania: "🇷🇴",
  bulgaria: "🇧🇬",
  croatia: "🇭🇷",
  ukraine: "🇺🇦",
  "hong-kong": "🇭🇰",
  taiwan: "🇹🇼",
  bangladesh: "🇧🇩",
  pakistan: "🇵🇰",
  "sri-lanka": "🇱🇰",
  israel: "🇮🇱",
  tunisia: "🇹🇳",
  cyprus: "🇨🇾",
  kenya: "🇰🇪",
  ghana: "🇬🇭",
  tanzania: "🇹🇿",
  uganda: "🇺🇬",
  rwanda: "🇷🇼",
  senegal: "🇸🇳",
  algeria: "🇩🇿",
  zambia: "🇿🇲",
  uruguay: "🇺🇾",
  ecuador: "🇪🇨",
  bolivia: "🇧🇴",
  paraguay: "🇵🇾",
  venezuela: "🇻🇪",
  anguilla: "🇦🇮",
  "antigua-and-barbuda": "🇦🇬",
  aruba: "🇦🇼",
  "british-virgin-islands": "🇻🇬",
  "cayman-islands": "🇰🇾",
  curacao: "🇨🇼",
  "curaçao": "🇨🇼",
  dominica: "🇩🇲",
  grenada: "🇬🇩",
  guadeloupe: "🇬🇵",
  martinique: "🇲🇶",
  montserrat: "🇲🇸",
  "saint-kitts-and-nevis": "🇰🇳",
  "saint-lucia": "🇱🇨",
  "saint-maarten": "🇸🇽",
  "saint-martin": "🇲🇫",
  "saint-vincent-and-the-grenadines": "🇻🇨",
  "turks-and-caicos-islands": "🇹🇨",
  "us-virgin-islands": "🇻🇮",
  "u-s-virgin-islands": "🇻🇮",
};

const LABEL_ALIASES: Record<string, string> = {
  "united states": "usa",
  "united kingdom": "uk",
  "united arab emirates": "uae",
  "south korea": "south-korea",
  "czech republic": "czechia",
  "hong kong": "hong-kong",
  "sri lanka": "sri-lanka",
  "south africa": "south-africa",
  "saudi arabia": "saudi-arabia",
  "costa rica": "costa-rica",
  "dominican republic": "dominican-republic",
  "trinidad and tobago": "trinidad-and-tobago",
  "puerto rico": "puerto-rico",
  "cayman islands": "cayman-islands",
  "british virgin islands": "british-virgin-islands",
  "u.s. virgin islands": "us-virgin-islands",
  "us virgin islands": "us-virgin-islands",
  "antigua and barbuda": "antigua-and-barbuda",
  "saint kitts and nevis": "saint-kitts-and-nevis",
  "saint lucia": "saint-lucia",
  "saint maarten": "saint-maarten",
  "saint martin": "saint-martin",
  "saint vincent and the grenadines": "saint-vincent-and-the-grenadines",
  "turks and caicos islands": "turks-and-caicos-islands",
  curacao: "curacao",
  "curaçao": "curacao",
};

export function resolveCountryFlagSlug(countryId: string): string {
  const slug = normalizeCountrySlug(countryId);
  return SLUG_ALIASES[slug] ?? slug;
}

export function getCountryFlag(countryId: string): string {
  const slug = resolveCountryFlagSlug(countryId);
  return COUNTRY_FLAGS[slug] ?? "🌍";
}

/** Flag from a human country name (e.g. regional coverage lists). */
export function flagForCountryLabel(label: string): string {
  const key = label.trim().toLowerCase();
  const mapped = LABEL_ALIASES[key];
  if (mapped) return getCountryFlag(mapped);
  return getCountryFlag(normalizeCountrySlug(label));
}

/** Prefer API flag when present; otherwise use local catalog. */
export function resolveCountryFlag(
  countryId: string,
  apiFlag?: string | null,
): string {
  const trimmed = apiFlag?.trim();
  if (trimmed) return trimmed;
  return getCountryFlag(countryId);
}
