/**
 * Country photo registry — synced from public/images/destinations/.
 * Run: node scripts/sync-country-images.mjs
 *
 * Add a photo: drop `{country-slug}.webp` (or .jpg) in public/images/destinations/, then sync.
 */
export const COUNTRY_IMAGE_REGISTRY: Record<string, string> = {
  "algeria": "/images/destinations/algeria.jpg",
  "argentina": "/images/destinations/argentina.webp",
  "aruba": "/images/destinations/aruba.jpg",
  "australia": "/images/destinations/australia.webp",
  "austria": "/images/destinations/austria.webp",
  "bahamas": "/images/destinations/bahamas.webp",
  "bahrain": "/images/destinations/bahrain.webp",
  "bangladesh": "/images/destinations/bangladesh.jpg",
  "barbados": "/images/destinations/barbados.webp",
  "belgium": "/images/destinations/belgium.webp",
  "belize": "/images/destinations/belize.jpg",
  "bolivia": "/images/destinations/bolivia.jpg",
  "brazil": "/images/destinations/brazil.webp",
  "bulgaria": "/images/destinations/bulgaria.jpg",
  "cambodia": "/images/destinations/cambodia.jpg",
  "canada": "/images/destinations/canada.webp",
  "cayman-islands": "/images/destinations/cayman-islands.jpg",
  "chile": "/images/destinations/chile.webp",
  "china": "/images/destinations/china.webp",
  "colombia": "/images/destinations/colombia.webp",
  "costa-rica": "/images/destinations/costa-rica.webp",
  "croatia": "/images/destinations/croatia.jpg",
  "cyprus": "/images/destinations/cyprus.jpg",
  "czechia": "/images/destinations/czechia.jpg",
  "denmark": "/images/destinations/denmark.webp",
  "dominican-republic": "/images/destinations/dominican-republic.webp",
  "ecuador": "/images/destinations/ecuador.jpg",
  "egypt": "/images/destinations/egypt.webp",
  "ethiopia": "/images/destinations/ethiopia.jpg",
  "fiji": "/images/destinations/fiji.webp",
  "finland": "/images/destinations/finland.webp",
  "france": "/images/destinations/france.webp",
  "germany": "/images/destinations/germany.webp",
  "ghana": "/images/destinations/ghana.jpg",
  "greece": "/images/destinations/greece.jpg",
  "guatemala": "/images/destinations/guatemala.jpg",
  "honduras": "/images/destinations/honduras.jpg",
  "hong-kong": "/images/destinations/hong-kong.jpg",
  "hungary": "/images/destinations/hungary.jpg",
  "iceland": "/images/destinations/iceland.webp",
  "india": "/images/destinations/india.webp",
  "indonesia": "/images/destinations/indonesia.webp",
  "ireland": "/images/destinations/ireland.webp",
  "israel": "/images/destinations/israel.jpg",
  "italy": "/images/destinations/italy.webp",
  "jamaica": "/images/destinations/jamaica.webp",
  "japan": "/images/destinations/japan.webp",
  "jordan": "/images/destinations/jordan.webp",
  "kenya": "/images/destinations/kenya.jpg",
  "kuwait": "/images/destinations/kuwait.webp",
  "lebanon": "/images/destinations/lebanon.webp",
  "malaysia": "/images/destinations/malaysia.webp",
  "maldives": "/images/destinations/maldives.webp",
  "malta": "/images/destinations/malta.webp",
  "mexico": "/images/destinations/mexico.webp",
  "morocco": "/images/destinations/morocco.webp",
  "netherlands": "/images/destinations/netherlands.webp",
  "new-zealand": "/images/destinations/new-zealand.jpg",
  "nigeria": "/images/destinations/nigeria.webp",
  "norway": "/images/destinations/norway.webp",
  "oman": "/images/destinations/oman.webp",
  "pakistan": "/images/destinations/pakistan.jpg",
  "panama": "/images/destinations/panama.webp",
  "paraguay": "/images/destinations/paraguay.jpg",
  "peru": "/images/destinations/peru.webp",
  "philippines": "/images/destinations/philippines.webp",
  "poland": "/images/destinations/poland.jpg",
  "portugal": "/images/destinations/portugal.webp",
  "puerto-rico": "/images/destinations/puerto-rico.webp",
  "qatar": "/images/destinations/qatar.webp",
  "romania": "/images/destinations/romania.jpg",
  "russia": "/images/destinations/russia.webp",
  "rwanda": "/images/destinations/rwanda.jpg",
  "saudi-arabia": "/images/destinations/saudi-arabia.webp",
  "senegal": "/images/destinations/senegal.jpg",
  "singapore": "/images/destinations/singapore.webp",
  "south-africa": "/images/destinations/south-africa.webp",
  "south-korea": "/images/destinations/south-korea.webp",
  "spain": "/images/destinations/spain.webp",
  "sri-lanka": "/images/destinations/sri-lanka.jpg",
  "sweden": "/images/destinations/sweden.webp",
  "switzerland": "/images/destinations/switzerland.webp",
  "taiwan": "/images/destinations/taiwan.jpg",
  "tanzania": "/images/destinations/tanzania.jpg",
  "thailand": "/images/destinations/thailand.webp",
  "trinidad-and-tobago": "/images/destinations/trinidad-and-tobago.webp",
  "tunisia": "/images/destinations/tunisia.jpg",
  "turkey": "/images/destinations/turkey.webp",
  "uae": "/images/destinations/uae.webp",
  "uganda": "/images/destinations/uganda.jpg",
  "uk": "/images/destinations/uk.webp",
  "ukraine": "/images/destinations/ukraine.jpg",
  "uruguay": "/images/destinations/uruguay.jpg",
  "usa": "/images/destinations/usa.webp",
  "venezuela": "/images/destinations/venezuela.jpg",
  "vietnam": "/images/destinations/vietnam.webp",
  "zambia": "/images/destinations/zambia.jpg",
};

/** Regional multi-country products only — never used as a stand-in for a single country. */
export const REGIONAL_IMAGE_REGISTRY: Record<string, string> = {
  "africa": "/images/destinations/africa-regional.webp",
  "americas": "/images/destinations/north-america-regional.webp",
  "asia-pacific": "/images/destinations/asia-regional.webp",
  "caribbean": "/images/destinations/caribbean-regional.webp",
  "europe": "/images/destinations/europe-regional.webp",
  "global": "/images/destinations/global-regional.webp",
  "middle-east": "/images/destinations/middle-east-regional.webp",
  "north-america": "/images/destinations/north-america-regional.webp",
  "south-america": "/images/destinations/south-america-regional.webp",
};
