import type { OutreachContact } from "@/lib/outreach-types";

/** Starter list from our micro-creator search — edit freely in the CRM. */
export const OUTREACH_SEED_CONTACTS: Omit<
  OutreachContact,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Saffiyah",
    handle: "@saffiyah.travels",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/saffiyah.travels/",
    contentUrl: "",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "Solo Muslim travel + Umrah tips; nano-tier.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Naima Begum",
    handle: "@muslimsgotravel",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/muslimsgotravel/",
    contentUrl: "https://muslimsgotravel.com/",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "Budget/halal travel; group trips = possible group codes.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Hadia",
    handle: "@lifewithhadz",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/lifewithhadz/",
    contentUrl:
      "https://www.instagram.com/lifewithhadz/reel/C04jtLqgHJB/",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "Umrah packing reel — practical logistics.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Tasneem Sayanvala",
    handle: "",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/reel/DJCCexSTJlo/",
    contentUrl: "https://www.instagram.com/reel/DJCCexSTJlo/",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "DIY Umrah from UAE→Jeddah; packing + hotels. Confirm IG handle from the reel profile.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Pakladies",
    handle: "Pakladies",
    email: "",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/watch?v=b_3yPHikEmQ",
    contentUrl: "https://www.youtube.com/watch?v=b_3yPHikEmQ",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "Umrah packing tips — first Umrah Spain to Jeddah.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Usman Tahir Jappa",
    handle: "Usman Tahir Jappa",
    email: "",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/watch?v=7eBSiqgD9Qk",
    contentUrl: "https://www.youtube.com/watch?v=7eBSiqgD9Qk",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "Jeddah airport → Makkah arrival vlog — strong eSIM angle.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Aleeza Siddika",
    handle: "@aleezasiddika",
    email: "",
    platform: "tiktok",
    profileUrl: "https://www.tiktok.com/@aleezasiddika",
    contentUrl: "",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "UK Muslim family travel (TikTok).",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Farzana / Herquesting",
    handle: "@herquesting",
    email: "farzana.s.sultana@gmail.com",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/herquesting/",
    contentUrl: "",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "UK lifestyle/travel nano; open to affiliations. Email from public creator dir — confirm before send.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Ellie Quinn Belhaj",
    handle: "@thewanderingquinn",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/thewanderingquinn/",
    contentUrl: "https://www.thewanderingquinn.com/",
    wave: "2",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "UK revert travel; also @_equinn. Group trips = codes for attendees.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Amira Patel / Wanderlust Women",
    handle: "@the.wanderlust.women",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/the.wanderlust.women/",
    contentUrl: "https://www.thewanderlustwomen.co.uk/",
    wave: "2",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "Also @amira_thewanderlust. Community / retreat group codes.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Elena / Muslim Travel Girl",
    handle: "@muslimtravelgirl",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/muslimtravelgirl/",
    contentUrl: "https://muslimtravelgirl.com/",
    wave: "3",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "DIY Umrah authority — contact after early Wave 1 wins.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
];
