import type { OutreachContact } from "@/lib/outreach-types";

/** Starter list from our micro-creator search — edit freely in the CRM. */
export const OUTREACH_SEED_CONTACTS: Omit<
  OutreachContact,
  "id" | "createdAt" | "updatedAt"
>[] = [
  {
    name: "Saffiyah",
    handle: "@saffiyah.travels",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/saffiyah.travels/",
    contentUrl: "",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "Solo Muslim travel + Umrah tips. IG DM drafted then unsent (duplicate paste). Still need one clean resend.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Juber / Muslims Go Travel",
    handle: "@muslimsgotravel",
    email: "contact@muslimsgotravel.com",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/muslimsgotravel/",
    contentUrl: "https://muslimsgotravel.com/",
    wave: "1",
    status: "messaged",
    messageSent: "gifted_collab email via Resend (noreply@noorlink.co)",
    promoCode: "",
    notes:
      "Budget/halal travel. EMAIL SENT. (Seed previously misnamed Naima Begum.)",
    contactedAt: "2026-09-09T12:00:00.000Z",
    repliedAt: "",
    lastEmailAt: "2026-09-09T12:00:00.000Z",
    lastEmailSubject: "Gifted KSA eSIM + custom code for your followers",
  },
  {
    name: "Hadia",
    handle: "@lifewithhadz",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/lifewithhadz/",
    contentUrl:
      "https://www.instagram.com/lifewithhadz/reel/C04jtLqgHJB/",
    wave: "1",
    status: "messaged",
    messageSent: "IG DM from @noorlinkesim (typo HHi in opener)",
    promoCode: "",
    notes:
      "Umrah packing. IG DM SENT (live). Optional: fix HHi opener if she replies.",
    contactedAt: "2026-09-09T12:00:00.000Z",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Tasneem Sayanvala",
    handle: "",
    email: "",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/reel/DJCCexSTJlo/",
    contentUrl: "https://www.instagram.com/reel/DJCCexSTJlo/",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "DIY Umrah from UAE→Jeddah; packing + hotels. Confirm IG handle from the reel profile.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Pakladies",
    handle: "Pakladies",
    email: "",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/watch?v=b_3yPHikEmQ",
    contentUrl: "https://www.youtube.com/watch?v=b_3yPHikEmQ",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "Umrah packing tips — first Umrah Spain to Jeddah.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Usman Tahir Jappa",
    handle: "Usman Tahir Jappa",
    email: "",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/watch?v=7eBSiqgD9Qk",
    contentUrl: "https://www.youtube.com/watch?v=7eBSiqgD9Qk",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "Jeddah airport → Makkah arrival vlog — strong eSIM angle.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Aleeza Siddika",
    handle: "@aleezasiddika",
    email: "",
    platform: "tiktok",
    profileUrl: "https://www.tiktok.com/@aleezasiddika",
    contentUrl: "",
    wave: "1",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes: "UK Muslim family travel (TikTok).",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Farzana / Herquesting",
    handle: "@herquesting",
    email: "farzana.s.sultana@gmail.com",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/herquesting/",
    contentUrl: "",
    wave: "1",
    status: "messaged",
    messageSent: "gifted_collab email via Resend (noreply@noorlink.co)",
    promoCode: "",
    notes: "UK lifestyle/travel nano. EMAIL SENT.",
    contactedAt: "2026-09-09T12:00:00.000Z",
    repliedAt: "",
    lastEmailAt: "2026-09-09T12:00:00.000Z",
    lastEmailSubject: "Gifted KSA eSIM + custom code for your followers",
  },
  {
    name: "Ellie Quinn Belhaj",
    handle: "@thewanderingquinn",
    email: "thewanderingquinn@gmail.com",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/thewanderingquinn/",
    contentUrl: "https://www.thewanderingquinn.com/",
    wave: "2",
    status: "messaged",
    messageSent: "gifted_collab email via Resend (noreply@noorlink.co)",
    promoCode: "",
    notes:
      "UK revert travel; also @_equinn. EMAIL SENT.",
    contactedAt: "2026-09-09T12:00:00.000Z",
    repliedAt: "",
    lastEmailAt: "2026-09-09T12:00:00.000Z",
    lastEmailSubject: "Gifted KSA eSIM + custom code for your followers",
  },
  {
    name: "Amira Patel / Wanderlust Women",
    handle: "@the.wanderlust.women",
    email: "amirawanderlust@gmail.com",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/the.wanderlust.women/",
    contentUrl: "https://www.thewanderlustwomen.co.uk/",
    wave: "2",
    status: "messaged",
    messageSent: "gifted_collab email via Resend (noreply@noorlink.co)",
    promoCode: "",
    notes:
      "Also @amira_thewanderlust. EMAIL SENT.",
    contactedAt: "2026-09-09T12:00:00.000Z",
    repliedAt: "",
    lastEmailAt: "2026-09-09T12:00:00.000Z",
    lastEmailSubject: "Gifted KSA eSIM + custom code for your followers",
  },
  {
    name: "Elena / Muslim Travel Girl",
    handle: "@muslimtravelgirl",
    email: "hello@muslimtravelgirl.com",
    platform: "instagram",
    profileUrl: "https://www.instagram.com/muslimtravelgirl/",
    contentUrl: "https://muslimtravelgirl.com/",
    wave: "3",
    status: "messaged",
    messageSent: "gifted_collab email via Resend (noreply@noorlink.co)",
    promoCode: "",
    notes: "DIY Umrah authority. EMAIL SENT.",
    contactedAt: "2026-09-09T12:00:00.000Z",
    repliedAt: "",
    lastEmailAt: "2026-09-09T12:00:00.000Z",
    lastEmailSubject: "Gifted KSA eSIM + custom code for your followers",
  },

  // —— YouTube English / nano (search find) ——
  {
    name: "Uzbeen",
    handle: "@Uzbeen",
    email: "",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/@Uzbeen",
    contentUrl:
      "https://www.youtube.com/@Uzbeen/videos",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "YT ~4.4K. Ladies Umrah packing + Hajj/Umrah policy (Urdu/English). True nano. No public email — About/comment.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Arnza Diaries",
    handle: "@ArnzaDiaries",
    email: "",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/@ArnzaDiaries",
    contentUrl:
      "https://www.youtube.com/@ArnzaDiaries/videos",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "YT ~15K. DIY Umrah (visa, Nusuk, hotels, Haramain). English. Blog: arnzadiaries.blogspot.com.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Insaf Slim",
    handle: "@Insafthevisitor",
    email: "info@insaftv.co.uk",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/@Insafthevisitor",
    contentUrl:
      "https://www.youtube.com/watch?v=KZU-8RJsu7c",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "YT ~51K UK. Budget DIY Umrah / Wizz / Haramain. Public email in About. Micro not nano.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "HAJJ VLOGGER",
    handle: "@HajjVlogger",
    email: "Hajjvlogger@gmail.com",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/@hajjvlogger",
    contentUrl: "https://www.youtube.com/@hajjvlogger",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "YT ~33K Scotland/UK. Active Umrah 2026 tips/vlogs. IG @irfxn.ali. Email on channel.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Anam's Cooking and Lifestyle",
    handle: "@anamscookingandlifestyle",
    email: "",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/@AnamsCookingandLifestyle",
    contentUrl:
      "https://www.youtube.com/@AnamsCookingandLifestyle",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "YT ~1.2K. Pakistani mom in USA (NJ). America→Madinah Umrah prep + Hajj vlogs. Nano.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Wander with Zed",
    handle: "@wanderwithzed",
    email: "",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/@WanderwithZed",
    contentUrl:
      "https://www.youtube.com/@WanderwithZed",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "YT ~258 Toronto. Canada→Saudi Ramadan transit Umrah. IG @zainarshadd.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "HammadxTravel",
    handle: "@hammadxtravel",
    email: "",
    platform: "youtube",
    profileUrl: "https://www.youtube.com/@HammadxTravel",
    contentUrl:
      "https://www.youtube.com/@HammadxTravel",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "YT brand-new (~6). Adelaide AU solo Umrah. Site: hammadxhassan.com.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Travel With Tahir (US layover)",
    handle: "Travel With Tahir",
    email: "",
    platform: "youtube",
    profileUrl:
      "https://www.youtube.com/results?search_query=Umrah+During+12+Hour+Layover+from+USA+Travel+With+Tahir",
    contentUrl:
      "https://www.youtube.com/results?search_query=I+Challenged+Myself+to+do+Umrah+During+12+Hour+Layover",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "USA→Jeddah 12hr layover Umrah (~7K views). Confirm handle — not India moto @travelwithTahir.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Amna's vlog",
    handle: "Amna,s vlog",
    email: "",
    platform: "youtube",
    profileUrl:
      "https://www.youtube.com/results?search_query=Amna%2Cs+vlog+umrah+packing",
    contentUrl:
      "https://www.youtube.com/results?search_query=Amna%2Cs+vlog+umrah+packing",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "Ladies/family/baby Umrah packing. Small channel; open via search → About for email.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },

  // —— Masjids / Islamic centers / Umrah groups ——
  {
    name: "Al-Amin Center of Florida (Rawdah Express)",
    handle: "Al-Amin Center Florida",
    email: "info@rawdahexpress.com",
    platform: "email",
    profileUrl: "https://alamincenterflorida.org/umrah/",
    contentUrl: "https://alamincenterflorida.org/umrah/",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "Masjid Umrah Nov 20–28 2026 · Sheikh Qari Sajjad. Phone/WhatsApp 561-247-2587. Use masjid_umrah_group template.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Ibrahim Center",
    handle: "Ibrahim Center Houston",
    email: "connect@ibrahimcenter.org",
    platform: "email",
    profileUrl: "https://ibrahimcenter.org/umrah/",
    contentUrl: "https://ibrahimcenter.org/umrah/",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "Houston TX. Umrah Nov 21–28 2026 · Shaykh Khalis Rashaad. 618 Baca St. Use masjid_umrah_group.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "NYC Muslim Center",
    handle: "NYCMC",
    email: "",
    platform: "other",
    profileUrl: "https://www.nycmuslimcenter.org/umrah",
    contentUrl: "https://www.nycmuslimcenter.org/umrah",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "Umrah Nov 22–30 2026 · Sh. Shakiel Humayun / Sh. Zakareeya Baksh. Coord: Br. Afridi Hussein. Find public email on site/contact form.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Islamic Center of South Jersey",
    handle: "ICSJ / Imam Nauman Ahmad Khan",
    email: "",
    platform: "other",
    profileUrl:
      "https://sarainternationaltravel.com/packages/november-umrah-with-istanbul-trip/",
    contentUrl:
      "https://sarainternationaltravel.com/packages/november-umrah-with-istanbul-trip/",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "Nov 2026 JFK luxury Umrah via Sara Travel · Imam Nauman. Partner center first, not undercut agency.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Becca Center Chicago",
    handle: "Becca Center",
    email: "",
    platform: "other",
    profileUrl:
      "https://sarainternationaltravel.com/packages/november-platinum-umrah/",
    contentUrl:
      "https://sarainternationaltravel.com/packages/november-platinum-umrah/",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "Nov 25–Dec 5 2026 Platinum JFK Umrah via Sara. Confirm center contact independently of agency.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "MUHSEN Umrah",
    handle: "MUHSEN",
    email: "umrah@muhsen.org",
    platform: "email",
    profileUrl: "https://muhsen.org/",
    contentUrl: "https://dstworldtravel.com/muhsennovumrah/",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "Accessible Umrah Nov 20–29 2026 w/ Dar El Salam. Sr. Maheen 212-725-2022 x129. Sensitive — lead with accessibility support.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
  {
    name: "Islamic Society of Windsor",
    handle: "IS Windsor",
    email: "",
    platform: "other",
    profileUrl: "https://iswindsor.ca/umrah-2025/",
    contentUrl: "https://iswindsor.ca/umrah-2025/",
    wave: "search",
    status: "to_contact",
    messageSent: "",
    promoCode: "",
    notes:
      "Canada community Umrah host. Confirm 2026 dates + contact via site newsletter/form.",
    contactedAt: "",
    repliedAt: "",
    lastEmailAt: "",
    lastEmailSubject: "",
  },
];
